Added syslog.timestamp_format to configure dateFormat in syslog template
cloudfoundry/syslog-release pull request #63
Opened 2021-09-29 07:51 UTC by ading007

2021-10-06 16:06 UTC, bgandon requested changes
Thanks for your contribution.

You need to fix the error in your ERB code.
How have you tested your changes?

You should also consider reading the docs here that shows how to run the tests.
See: https://github.com/cloudfoundry/syslog-release/blob/main/README.md#development

2021-10-08 02:17 UTC, ading007 commented on jobs/syslog_forwarder/spec
> +
Thank you for your response, i will update my PR.

2021-10-19 17:02 UTC, Benjamintf1 commented
@ading007 Is there any reason given that, that we don't just use the dateinutc option?(havn't tried it) and a UTC boolean flag on the release in that case? 
![image](https://user-images.githubusercontent.com/2761008/137957041-181dd114-e4c0-47c3-b709-211f3bce4e52.png)

I'm actually a little surprised tbh that we arn't using utc by default anyways(perhaps this is a vm configuration that I'm not used to as well). Honestly, if the date.inUTC option works? then maybe it would be best to default inUTC on?

2021-11-01 16:44 UTC, bgandon commented
Timezone on Bosh VM instances is set to UTC, @Benjamintf1

2021-11-02 09:30 UTC, YanzhaoLi commented on jobs/syslog_forwarder/spec
> +        timestamp_format: utc
@ading007  Please change 194-196 lines to `example: utc`

2021-11-02 09:36 UTC, YanzhaoLi commented on jobs/syslog_forwarder/spec
> +      https://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html#property-options.
Hi @bgandon , thanks very much for figuring this out in detail.  How about changing it to
```
Sets the dateFormat in the syslog template.  All the property options with date- prefix can be accepted, see https://www.rsyslog.com/doc/v8-stable/configuration/templates.html#the-template-statement 
E.g: utc rfc3164..., for details, please see 
https://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html#property-options.
```

2021-11-02 09:50 UTC, YanzhaoLi commented
> Honestly, if the date.inUTC option works? then maybe it would be best to default inUTC on? (are we sure the datformat "utc" is always and will always be 3339?

I think we might need other dateFormat besides utc in the future.

2021-11-02 16:44 UTC, Benjamintf1 commented
Id highly doubt or discourage there being any use for a setting that's not 3339.

2021-11-03 07:02 UTC, YanzhaoLi commented
> Id highly doubt or discourage there being any use for a setting that's not 3339.

I just noted that you comment`RFC5424 specifies it MUST be 3339`, so I wonder whether we can get other date formats like utc but still use the 3339?

2021-11-03 17:13 UTC, Benjamintf1 commented
Seems like a pre-mature optimization in that sense that opens us up possibly to a lot of invalid configurations. (I'd still suspect we should generally be talking in utc, I'm surprised the underlying infra is reporting not in utc, but also that we don't translate). Given the core of this request is inability(or wish) not to translate regional timezones, I'd think addressing that directly seems the most prudent to me. 

That said, I'd like to re-point out that we don't have a signed cla on this issue, so it's going to make any other move forward on this pr imposssible regardless.

2021-11-04 14:23 UTC, YanzhaoLi commented
Sure. @ading007  Please sign the CLA first.

2021-11-05 11:48 UTC, bgandon commented on jobs/syslog_forwarder/spec
> +      https://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html#property-options.
Yes, nice 👍
Just wrap the text a bit around the 80th column in order to avoid long lines. That'll be my final advice.

2021-11-05 12:11 UTC, bgandon commented
I've read previous comments too quickly, sorry guys for that.

> _I'm surprised the underlying infra is reporting not in utc_

Yes you're right, that's strange indeed. I would have expected dates to be in UTC already.

> _Given the core of this request is inability(or wish) not to translate regional timezones, I'd think addressing that directly seems the most prudent to me._

After careful reading of the original requirement as exposed by @ading007 in https://github.com/cloudfoundry/syslog-release/pull/63#issuecomment-940635161 (please copy this to the PR description next time! this is important information that needs to appear upfront), that's a legitimate concern indeed. Thanks a lot @Benjamintf1 for raising it.

Providing a boolean property that would control the `date.inUTC="(on|off)"` option would be a better fit for the use-case.

@ading007, could you test that alternative implementation and let us know? If successful, then provide us with that alternative implementation instead? Thanks!

2021-12-09 16:45 UTC, closed without merging